### ISSUE TITLE
Adding some examples for using subcollections?

### ISSUE THREAD

**Issue by kirbyfan64** [acupajoe/elasticstore#1]
This library looks perfect for what I'm aiming to use in one of my projects, but right now the interactions between subcollections and everything else aren't really described too thoroughly.

**Comment by acupajoe** [comment]
Happy to add some more documentation! Did you have some specific questions?

**Comment by kirbyfan64** [comment]
Basically, from reading the docs, I can see that elasticstore will load the documents in the given Firestore collection into the index, but it's not clear how that interacts with subcollections. Say I have a collection `instances` and a subcollection `names`, e.g. then I can access it via `/instances/some-id-123456/names`:

- Where will it be saved in the index? Say I have `index: 'xyz'`. Will it be saved to `/xyz/some-id-123456/names` or `/xyz/some-id-123456` or something else?
- Should there be another item in `references` for the root collection?
- How should searches be run for subcollections?

Thanks for the quick reply!

**Comment by acupajoe** [comment]
Awesome, thanks for the clarifications! I'll ad a bit of a readme here and will adjust it on the repo when it's to your liking.

## Subcollections
When this repo was first made, Firestore had some limitations on how collections worked. You could have a root collection and every root Collection could have a Subcollection. Subcollections could not _not_ have Subcollections.

This repo supports the use of subcollections with the note that **this is expensive**. Why? Because when Firestore returns a Collection Query it does not return the Subcollection's data, meaning, to listen to changes on a Subcollection requires a listener **per Subcollection instance**.

Have a need for a Subcollection from 400 Collection instances? That's 400 listeners. AFAIK there's not a better way to do this given Firebase's current API.

So with those caveats, the repo allows you to specify some ways to narrow how many listeners you register by narrowing your queries.

**For Example**
```
// Firestore Data Model
{
  // Collection
  "users" : { 
      "UUID-1" : {
            email: "romeo@example.com",
            isPremium: true,
            // Subcollection
            "profile": { 
                 "firstName": "Romeo",
                  "public": false
                  ....
             } 
      } 
      "UUID-2" : {
            email: "juliet@example.com",
            isPremium: false,
            // Subcollection
            "profile": { 
                  "firstName": "Juliet"
                  "public": true,
                  ...
             } 
      } 
}
```

To listen to the `profile` Subcollection on `user` where the `profile` is public , you'd create a reference like this:
```
{
  collection: "users",
  subcollection: "profile",
  index: "user-profiles",
  type: "user-profiles",
  subBuilder: (ref) => ref.where('public', '==', true)
}
```

Or only `profile`s where the user `isPremium` and public (note that the index and type are changed, but that the change is arbitrary):
```
{
  collection: "users",
  subcollection: "profile",
  index: "user-premium-profiles",
  type: "user-premium-profiles",
  builder: (ref) => ref.where('isPremium', '==', false),
  subBuilder: (ref) => ref.where('public', '==', true)
}
```


Does that help?

**Comment by kirbyfan64** [comment]
@acupajoe Thanks, that's a lot better!! I have just *one* more question: it the `user-profiles` example, how does one access the UUID to tell the users apart?

**Comment by acupajoe** [comment]
That'd be in the `transform` function, for instance, adding the into the data being sent to elasticsearch would look something like this:
```
{
  // ...
  transform: (data, parentSnapshot) => { id: parentSnapshot.id, ...data}
}
```

* Where `parentSnapshot` is the `Firebase.Snapshot` of the containing collection.

**Comment by kirbyfan64** [comment]
@acupajoe Thank you so much! This is all so much clearer now.

**Comment by helloworldkr** [comment]
How do I access nested subcollection
For eg.
// Firestore Data Model
`{
  // Collection
  "users" : { 
      "UUID-1" : {
            email: "romeo@example.com",
            isPremium: true,
            // Subcollection
            "Notes": { 
                   "data": "Romeo",
                    "public": false
                  ....
             } ,
           "Folder":{
          "Name":"SecondFolder",
                    // Nested notes subcollection
                    "Notes":{
                                "data":"MyNotes"
            }                
          }

      } 
      "UUID-2" : {
            email: "juliet@example.com",
            isPremium: false,
            // Subcollection
           
            "profile": { 
                  "firstName": "Juliet"
                  "public": true,
                  ...
             } ,
         // Subcollection
           "profile": { 
                  "firstName": "Juliet"
                  "public": true,
                  ...
             } 
      } 
}`



How do I get the data of Notes subcollection which is inside Folder subcollection?

**Comment by acupofjose** [comment]
@helloworldkr this project does not support nested subcollections - sorry!
